### ISSUE TITLE
Pacote desnecessário

### ISSUE THREAD

**Issue by allanvobraun** [jefferson-calmon/codocx#1]
Esse pacote já é nativo do node, não precisa estar no package json.
https://github.com/jefferson-calmon/codocx/blob/0f6ee9c38ec99444aa7934c38e1021bcb7668027/package.json#L22C10-L22C23

**Comment by jefferson-calmon** [comment]
Fala @allanvobraun! Acabei de fazer um push com essa correção! 

Obrigado pela atenção!
